### PR TITLE
Support for external DockerHub Images

### PR DESCRIPTION
**Pull request by l4rm4nd**
Hey @robinkarlberg,

I've [forked your repository](https://github.com/l4rm4nd/transfer.zip-web) and implemented GitHub Actions quickly.

Afterwards, I also adjusted the provided `docker-compose.yml` to reflect the new information.

In order to merge, you have to:

- Create your GitHub repository secrets `DOCKER_HUB_ACCESS_TOKEN` and `DOCKER_HUB_USERNAME`. Basically your API token from Dockerhub and your username. You can create those on GitHub at https://github.com/robinkarlberg/transfer.zip-web/settings/secrets/actions
- Adjust the `.github/workflows/docker-image.yml` file (only the build tags) to hold your Dockerhub username + image + tags you want to use
- Adjust the `docker-compose.yml` file to reflect your Dockerhub image details

Cheers!

### CODE REVIEW

**Comment by mathiasmagnusson** [comment]
Just wondering what the value of making the `docker-compose.yaml` file use the images from dockerhub is? Running `docker compose up -d` (with nothing being cached) takes about 20 seconds on my laptop so this will most likely not speed it up much.

Also, isn't it a bad idea to put both images in the same image but with different tags? Tags are usually used to separate different versions or variants of the same image, not two different images that should be run together.

**Comment by mathiasmagnusson** [comment]
Running `docker pull l4rm4nd/transferzip:web-server && docker pull l4rm4nd/transferzip:signaling-server` also took about 20 seconds on my laptop.

**Comment by l4rm4nd** [comment]
It is not about speed, but convenience. People do not have to clone this repository and build the container image locally. They can just pull the image from Dockerhub and are good to go.

Regarding tags, it's up to the maintainer. You are right though that tags usually indicate a version. However, if the maintainer only publishes latest code, we can misuse tags for simplicity.

In the end, it's just a suggestion. You can keep building from source locally. I won't.

**Comment by mathiasmagnusson** [comment]
Yes, I definitely see a point in publishing the images to a registry and was more asking about making the docker compose file by default pull from a registry.

I'm thinking that if you have the docker compose file you probably also have the repository and therefore might as well build the images yourself. But maybe I'm wrong?

**Comment by l4rm4nd** [comment]
> Yes, I definitely see a point in publishing the images to a registry and was more asking about making the docker compose file by default pull from a registry.
> 
> I'm thinking that if you have the docker compose file you probably also have the repository and therefore might as well build the images yourself. But maybe I'm wrong?

Docker Compose files usually reference external images. Building locally is just a user preference. Note that you can keep the build tag within the compose file next to the image tag.

> Without any explicit user directives, Compose with Build support must first try to pull the image, then build from source if the image was not found on registry.

https://docs.docker.com/compose/compose-file/build/#consistency-with-image

**Comment by ma-04** [comment]
When developing software, it’s common to use images, such as Docker images, to package and distribute the application. During development, these images may need to be updated frequently as changes are made to the code. One way to do this is by building the images locally and then pushing them to a remote repository. However, this can make it difficult to monitor for updates and ensure that the latest version of the image is being used.

To make this process easier, some developers choose to set up an automated system for updating their images. This can involve using a continuous integration (CI) pipeline to automatically build and push new images whenever changes are made to the code. This can help ensure that the latest version of the image is always available and make it easier to monitor for updates.

**Comment by l4rm4nd** [comment]
> When developing software, it’s common to use images, such as Docker images, to package and distribute the application. During development, these images may need to be updated frequently as changes are made to the code. One way to do this is by building the images locally and then pushing them to a remote repository. However, this can make it difficult to monitor for updates and ensure that the latest version of the image is being used.
> 
> To make this process easier, some developers choose to set up an automated system for updating their images. This can involve using a continuous integration (CI) pipeline to automatically build and push new images whenever changes are made to the code. This can help ensure that the latest version of the image is always available and make it easier to monitor for updates.

Exactly. In this case, GitHub Actions act as CI pipeline. As soon as you push a code change, a GitHub action will be triggered that automatically builds a new image based on the actual, latest code base. You may also add further pipelines for code integrity checks, running tests etc.

**Comment by robinkarlberg** [comment]
I don't really see how downloading a docker image is easier than to just `git clone` and `docker compose up`. Also, I need to go through the hassle of creating a DockerHub account, which is not worth it for such a small convenience (if any) to others.

**Comment by ma-04** [comment]
Hi, 
I understand your concern about the convenience of downloading a Docker image versus cloning the repository and building the images locally. While it may seem like a small convenience gain, using a pre-built image from a registry like DockerHub can save time and effort in the long run, especially when it comes to monitoring for updates and ensuring that the latest version of the image is being used.

For example, you can use tools like Ansible to automate the process of pulling the latest image from DockerHub and updating/deploying your containers. This can help streamline your workflow and make it easier to manage your containers. Ultimately, it’s up to you to decide which approach works best for your needs. 😊

I hope this helps clarify the benefits of using pre-built images from a registry like DockerHub. However, if you prefer to build the images locally, that is also a valid option.

**Comment by robinkarlberg** [comment]
Thank you ChatGPT! Now I am 100% convinced!

**Pull request closed without merging**
